CREATE DATABASE HARNESS;

CREATE TABLE T001_USER (
    USER CHAR(20) NOT NULL,
	PASSWORD CHAR(20) NOT NULL,
	CREATE_USER CHAR(20) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATE_USER CHAR(20),
	UPDATE_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (USER)
);

CREATE TABLE T002_TEST_SUITE (
    TEST_SUITE_ID INT NOT NULL AUTO_INCREMENT,
	TEST_SUITE_NAME CHAR(255) NOT NULL,
	TEST_SUITE_DESC CHAR(255),
	CREATE_USER CHAR(20) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATE_USER CHAR(20),
    UPDATE_TIMESTAMP TIMESTAMP,	
    PRIMARY KEY (TEST_SUITE_ID)
);

CREATE TABLE T003_TEST_CASE (
	TEST_CASE_ID INT NOT NULL AUTO_INCREMENT,
    TEST_SUITE_ID INT NOT NULL,
	TEST_CASE_NAME CHAR(255) NOT NULL,
	TEST_CASE_DESC CHAR(255),
	CREATE_USER CHAR(20) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATE_USER CHAR(20),
    UPDATE_TIMESTAMP TIMESTAMP,	
    PRIMARY KEY (TEST_CASE_ID),
	FOREIGN KEY (TEST_SUITE_ID)
		REFERENCES T002_TEST_SUITE(TEST_SUITE_ID)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE T004_TEST_STEPS (
	TEST_STEP_ID INT NOT NULL AUTO_INCREMENT,
    TEST_CASE_ID INT NOT NULL,
	STEP_NAME CHAR(255) NOT NULL,
	ELEMENT_ID INT NOT NULL,
	ELEMENT_TYPE CHAR(1) NOT NULL,
	ELEMENT_LOC_TYPE CHAR(1) NOT NULL,
	ELEMENT_LOC CHAR(255) NOT NULL,
	ACTION CHAR(1) NOT NULL,
	WAIT_TYPE CHAR(1),
	WAIT_TIME INT,
	IS_ACTIVE BOOLEAN,	
	CREATE_USER CHAR(20) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATE_USER CHAR(20),
    UPDATE_TIMESTAMP TIMESTAMP,	
    PRIMARY KEY (TEST_STEP_ID),
	FOREIGN KEY (TEST_CASE_ID)
		REFERENCES T003_TEST_CASE(TEST_CASE_ID)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE T004_TEST_STEPS ADD INDEX (ELEMENT_ID);

CREATE TABLE T005_TEST_DATA (
	TEST_DATA_ID INT NOT NULL AUTO_INCREMENT,
    ELEMENT_ID INT NOT NULL,
	ELEMENT_DATA CHAR(255) NOT NULL,	
	CREATE_USER CHAR(20) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATE_USER CHAR(20),
    UPDATE_TIMESTAMP TIMESTAMP,	
    PRIMARY KEY (TEST_DATA_ID),
	INDEX(ELEMENT_ID),
	FOREIGN KEY (ELEMENT_ID)
		REFERENCES T004_TEST_STEPS(ELEMENT_ID)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

